### ISSUE TITLE
Alternatives when Emacs is build without --with-xwidgets

### ISSUE THREAD

**Issue by buhtz** [seagle0128/grip-mode#22]
Thanks a lot for that package and the great documentation. You also take `use-package` into account which is unusual. Thanks for that!

It seams like that my Emacs 27.1 (Debian 11) was not build with `--with-xwidgets`. Even when I do `(setq grip-preview-use-webkit t)` the preview is opened in my systems default browser.

But I still want to have the preview in a second buffer.

Are you aware of any elpa browser packages that could be used in such a case?

**EDIT**: I learned about `eww-mode`. I am not sure how to connect that with grip. But normal websites and also README.md files from some GitHub pages looking ugly. That is not what I understand about a HTML rendered preview.

**Comment by seagle0128** [comment]
I don't recommend `eww-mode` with `grip-mode` due to the poor user experience. The external browser or webkit-widget are much better to preview the markdown file. AFIAK, there is no other elpa packages are alternative.

Another option may be [EAF](https://github.com/emacs-eaf/emacs-application-framework), but it's heavy to me.
