### ISSUE TITLE
Explain "ox-gfm"

### ISSUE THREAD

**Issue by buhtz** [seagle0128/grip-mode#25]
Hi,

from your README it is not clear for me what ox-gfm is, what for do I need it and how to setup it up and connect it with your package.

Maybe you can improve your README/FAQ with that info.

Kind
Christian

**Comment by seagle0128** [comment]
Please see the link: https://github.com/larstvei/ox-gfm.

**Comment by buhtz** [comment]
Of course I looked there. It is not clear for me what it is or how it is connected to your package. Simply two sentences from your site would be nice to your users.

**Comment by seagle0128** [comment]
>Instant Github-flavored Markdown/Org preview using [Grip](https://github.com/joeyespo/grip) (GitHub Readme Instant Preview).
[ox-gfm](https://github.com/larstvei/ox-gfm) is optional, but it brings better rendering for org files.

`grip-mode` supports to render both org and md files. For org files, it will be exported to md via `ox-md` or `ox-gfm`, and then be rendered by `grip`. `ox-gfm` is optional, since `ox-md` is built-in.
I don't think it's neccessary to broadcast to all users. All details are in the codes.
